---
title: Laura Lechner | Filmmaker
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  project:
    title: Project
    output: true
  regular_page:
    title: Regular Page
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: regular_page
  values:
    layout: default
- scope:
    path: ''
    type: project
  values:
    layout: default
email: laura@lauralechner.com
description: 'Laura Lechner is a filmmaker based in New York City '
baseurl: 
url: https://nbuonin.github.io/lauralechner-2
linkedin_url: https://www.linkedin.com/in/lalechner
vimeo_url: https://vimeo.com/lauralechner
facebook_url: https://www.facebook.com/kimthefilm/?fref=ts
markdown: kramdown
plugins:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- Makefile
sass:
  sass_dir: _scss
